### ISSUE TITLE
Update INSTALL file

### ISSUE THREAD

**Issue by maloy-ghosh** [guoxiao/terminator-gtk3#2]
There were few extra packages I had to install in ubuntu 16.04  LTS to run terminator out-of-the-box.
-  Error: No module named psutil
-  Error: Namespace GConf not available
  
     Ubuntu: **gir1.2-gconf-2.0**
- Error: Namespace Keybinder not available
  
    Ubuntu: **gir1.2-keybinder-3.0**

I am not sure about FreeBSD as I do not have one installed.

**Comment by guoxiao** [comment]
This is only a mirror of https://code.launchpad.net/~gnome-terminator/terminator/gtk3 .
If you have some suggestions or bug reports, please sent them to https://bugs.launchpad.net/terminator/+filebug
